name: Current Branch Name
description: Gets and sanitizes the current branch name or tag for the workflow.
author: Octopus Deploy
runs:
  using: node20
  main: index.js
inputs:
  github_ref:
    description: "The input for the github.ref. NOTE: this value should not need to be provided, unless you need to override the default."
    required: false
    default: ${{ github.ref }}
  github_head_ref:
    description: "The input for the github.head_ref. NOTE: this value should not need to be provided, unless you need to override the default."
    required: false
    default: ${{ github.head_ref }}
  github_event_name:
    description: "The input for the github.event_name. NOTE: this value should not need to be provided, unless you need to override the default."
    required: false
    default: ${{ github.event_name }}
  additional_strings_to_replace:
    description: "A multiline string of values to replace in the branch name. Default value of /"
    required: false
    default: "/"
  replacement_value:
    description: "The value to replace replacement_strings with. Default value of -."
    required: false
    default: "-"
outputs:
  branch_name:
    description: "Returns the current branch for the repository if the github ref is not a tag."
