name: Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: "full"
