name: Renovate
on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v29.36.2
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug
